### ISSUE TITLE
Login authentication 방식

### ISSUE THREAD

**Issue by tyj9327** [swsnu/swpp2019-team12#10]
Login authentication을 Frontend와 Backend 중 어디서 처리해야 하는지에 관한 논의 필요

Frontend에서 로그인이 되지 않은 유저는 초기 페이지로 라우팅하므로 Backend에서 is_authenticated 을 통해 확인할 필요가 없을 것 같은데, 그럼에도 더블체크를 하는 것이 옳을지, 아니면 하지 않아도 될지에 대해 논의해야 할 것 같습니다.

**Comment by Imchaemin** [comment]
더블체크하면 더 좋을거 같지만 mid 까진 없이 해도 될거같습니다
