### ISSUE TITLE
API 수정사항

### ISSUE THREAD

**Issue by tyj9327** [swsnu/swpp2019-team12#11]
**1. `/profile/:id/` 추가**
- GET: 특정 프로필 반환
- PATCH: 특정 프로필 정보 수정

**2. `/user/:id/` 삭제**
- `/profile/:id/` 로 통합

**3. 모든 블록 수정사항**
  1.  각 블록별로 `/workspace/:w_id/notes/n_id/[block]/`로 접근해서  해당 workspace와 note에 속하는 모든 블록을 불러오도록 url이 짜여져 있습니다. 하지만 다음과 같은 문제점이 있습니다. 
 _(1) workspace와 상관없이 notes들은 고유 id가 있기 때문에 workspace의 id가 필요하지 않음 
 (2) 현재 이 api를 호출하는 component가 note인지 agenda인지에 대한 정보가 없음 (is_parent_note를 특정할 수 없음)_
그러므로 `/parent/p_id/[block]/is_parent_note/` 로 api url을 변경하는 것을 건의합니다. 여기에서 is_parent_note는 String으로 True/False를 넣으면 될 것 같습니다. 

- 예를 들어 Frontend에서 id=2인 Note Container에 속한 id=3인 Agenda Container에서 Calendar Component를 가져와야한다면, `/parent/3/calendar/False/` 로 호출하고, 다른 예시로 id=1인 Note Container에서 직접 Todo Component를 가져와야한다면, `/parent/1/todo/True/` 로 호출하면 됩니다. 

- **다른 대안**으로, 위의 예시를 각각 `/agenda/3/calendar/`와 `/note/1/todo/` 로 나누어 호출하는 것도 생각해볼 수 있습니다. 즉, `/agenda/:id/[block]/` 과 `/note/:id/[block]` 의 두 API로 나누어 구현하는 것입니다. 이 경우 자동적으로 agenda가 url의 시작이라면 is_parent_note = False로 필터링할 수 있고, 반대도 가능합니다. 

2.  역시 각 블록별로 `/workspace/:w_id/notes/:n_id/[block]/:id/`로 접근해서 해당 workspace와 note에 속하는 특정 블록을 찾아올 수 있도록 url이 짜여있습니다. 역시 다음과 같은 문제점이 있습니다. 
_(1) workspace와 상관없이 notes들은 고유 id가 있기 때문에 workspace의 id가 필요하지 않음
(2) 나아가 각 블록별 id 역시 고유하므로 note의 id가 필요하지 않음_
그러므로 `/[block]/:id/`로 api url을 변경하는 것을 건의합니다. 

의견 부탁드려요!

**Comment by Imchaemin** [comment]
> 다른 대안으로, 위의 예시를 각각 /agenda/3/calendar/와 /note/1/todo/ 로 나누어 호출하는 것도 생각해볼 수 있습니다. 즉, /agenda/:id/[block]/ 과 /note/:id/[block] 의 두 API로 나누어 구현하는 것입니다. 이 경우 자동적으로 agenda가 url의 시작이라면 is_parent_note = False로 필터링할 수 있고, 반대도 가능합니다.

이 방법으로 적용하시죠!

모든 블록 호출 API 수정안
```
// Note 속 블록 호출
/note/:n_id/block

// Agenda 속 블록 호출
/agenda/:a_id/block
```
