### ISSUE TITLE
[BE] API 수정해야 할 부분.

### ISSUE THREAD

**Issue by NSYT0607** [swsnu/swpp2019-team12#12]
1. UserSerializer에서 create는 그냥 objects.create()와 동일하여 user model에 대해선 password를 제대로 설정하지 못하는 부분.

2. /api/signup/ POST에서 정상적으로 가입된 후에, response로 해당 user의 id를 반환해야하는데 
username과 password가 반환된다. (그리고 이거 password 같은 경우에는 해싱되서 나오는거라 뭐 잘은 모르겠지만, 안보여주는게 맞는 것 같음)

**Comment by tyj9327** [comment]
1. 해결 완료
2. /api/signup/POST 에서 profile까지 생성해주도록 변경하여 id 반환할 필요 없어짐. username과 password 반환하지 않도록 수정 완료.
