### ISSUE TITLE
[BE/API] User search / Workspace Search API 구현 필요

### ISSUE THREAD

**Issue by Imchaemin** [swsnu/swpp2019-team12#39]
1. 현재 workspace에서 새로운 member를 추가할 때
2. 새로운 workspace 생성시 member를 추가할 때

두 경우에서 입력하는 email 에 따라 해당되는 유저를 찾아주는 filter 기능이 필요할 것 같습니다.
세부 스펙은 아래와 같으면 되지 않을까 싶습니다

- API `GET user/:email`
- Response
  - Req에서 보내는 email에 일치하는 부분이 있는 유저들
  - 예시
    - Req : "test"
    - Res : `[ {id: 1, email: test_qwerty@google.com, ...}, ... ]`

마찬가지로 workspace 모두를 가져오는 것도 필요할 것 같습니다

**Comment by tyj9327** [comment]
넵 그런 방식으로 추가하면 될 것 같네요.

**Comment by Imchaemin** [comment]
> 넵 그런 방식으로 추가하면 될 것 같네요.

작업 한번 해보겠숩니다!
