### ISSUE TITLE
[FE/BE]User Auth 개선

### ISSUE THREAD

**Issue by tyj9327** [swsnu/swpp2019-team12#68]
## 문제점
1. 로그인 실패시 로그인 실패와 관련된 alert가 없음 (FE)
2. 로그인 성공 후, 현재 로그인 된 user 에 대해 알 수 없음 (상태바 추가할 필요성) (FE)
3. 로그아웃 구현이 안되어있음 (FE)
4. 로그인하지 않은 상태에서도 url로 모든 리소스에 접근 가능함 (FE/BE)
5. 가입시 비밀번호 공개 기능 없음 (optional)
6. 닉네임 수정기능 없음 (optional)

**Comment by NSYT0607** [comment]
1. 로그인 실패(아이디 존재하지 않거나, 비밀번호 틀린 경우)하면 "가입하지 않은 아이디이거나, 잘못된 비밀번호입니다. 메시지 출력.

3. <SignOut history={}/>의 형태로 가져다 쓰면 됩니다.
