### ISSUE TITLE
[FE/BE]Drag and drop 후 위치정보 저장

### ISSUE THREAD

**Issue by tyj9327** [swsnu/swpp2019-team12#85]
모델에 위치정보 (현재 사용중인 layer 활용해도 될듯) 저장해서 다시 불러올 때 정렬할 필요
- delete를 구현하기 위해서도 필요한 작업임

## 방식 후보
1. 각 블록들이 고유의 위치정보를 가지고 있도록 구현
2. 노트가 자신이 가지고 있는 blocks state를 db에 stringify해서 그대로 저장

**Comment by Imchaemin** [comment]
delete에는 어떻게 필요한거져?

**Comment by tyj9327** [comment]
생각해보니 그냥 for문 돌면서 매칭되는 block을 지워도 되긴 하겠네요
