### ISSUE TITLE
Model들에 대한 추가 고려사항

### ISSUE THREAD

**Issue by tyj9327** [swsnu/swpp2019-team12#9]
1. Image 모델에서 이미지 설명을 위한 caption field를 추가하는 것이 어떨까요?

2. File 모델의 경우 FileField를 사용해서 파일을 저장할 수 있습니다. 따로 url field를 만들기로 했었는데, 그냥 content field를 FileField로 저장하고 url field는 삭제하는 것이 어떤가요?

3. Calendar, Table 모델의 content field를 어떻게 저장해야 하는지에 대해 논의할 필요가 있습니다.

**Comment by Imchaemin** [comment]
> Image 모델에서 이미지 설명을 위한 caption field를 추가하는 것이 어떨까요?
- 매우 좋습니다

> File 모델의 경우 FileField를 사용해서 파일을 저장할 수 있습니다. 따로 url field를 만들기로 했었는데, 그냥 content field를 FileField로 저장하고 url field는 삭제하는 것이 어떤가요?
- 넵 SQL에서 지원하는 기능이있다면 그걸 쓰는게 좋겠져?

> Calendar, Table 모델의 content field를 어떻게 저장해야 하는지에 대해 논의할 필요가 있습니다.
- 넵넵 어서 정하긴 해야겠네요. 근데 일단 string 혹은 string[] 으로 필드하나만 만들어놔주세용
